name: recomendo
description: Recomending stuff

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: any
  path_provider: any
  intl: ^0.15.8
  location: any
  datetime_picker_formfield: 0.1.8
  image_picker: any
  flutter_map: 0.7.0
  cupertino_icons: ^0.1.2
  audio_recorder: 1.0.1
  permission_handler: ^3.2.1
  uuid: ^2.0.1
  audioplayers: ^0.13.1
  # scoped_model: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg

